### ISSUE TITLE
Lodash is used without being added to the dependencies

### ISSUE THREAD

**Issue by gabrielcolson** [bitfinexcom/bfx-api-node-util#17]
#### Issue type
- [X] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
Lodash is imported without being added to the dependencies. This behavior is unsafe and [yarn's Plug’n’Play feature doesn’t allow it](https://classic.yarnpkg.com/en/docs/pnp/troubleshooting/#toc-is-trying-to-require-without-it-being-listed-in-its-dependencies).

#### Steps to reproduce
```js
// test.js
require('bfx-api-node-util');
```

```bash
npm install -g yarn
yarn init -y
yarn set version berry
yarn add bfx-api-node-util
yarn node test.js
```

##### Additional Notes:
Lodash is used at only one place and there is a [native alternative](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_reverse). A better solution than adding lodash to the dependencies would be to use `Array.reverse()` instead.

**Comment by michael34435** [comment]
lodash is missing! please fix it!

**Comment by robertkowalski** [comment]
thanks for reporting, we'll release a fix shortly
