### ISSUE TITLE
Invalid 'main' field in package.json' of './dist/index.js'.

### ISSUE THREAD

**Issue by dutu** [bitfinexcom/bfx-api-node-util#19]
#### Issue type
- [x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
Entry `main` in `package.json` points to nonexistent file `./dist/index.js`.

node.js 16.0 issues warning:
`[DEP0128] DeprecationWarning: Invalid 'main' field in 'node_modules\bfx-api-node-util\package.json' of './dist/index.js'.`

#### Steps to reproduce
Check `package.json`
To see the warning, use the module in node.js 16.0.

##### Additional Notes:
-

**Comment by robertkowalski** [comment]
fixed in #20
