### ISSUE TITLE
Cannot find module 'bfx-api-node-models' in v1.0.4

### ISSUE THREAD

**Issue by chrisLeeTW** [bitfinexcom/bfx-api-node-util#8]
#### Issue type
- [ X ] bug

#### Brief description

Use package "bfx-api-node-models" in lib/res_notification_info.js which is located in devDependencies.

It will be broken when you use it in production (will not install devDependencies XD).

**Comment by chrisLeeTW** [comment]
ping @f3rno @prdn @ezewer @JacobPlaster 

I think this is very serious problem. It is currently broken my lending robots which I use bitfinex-api-node sdk. ):

**Comment by ezewer** [comment]
@chrisLeeTW strange is working fine for me, however returning to npm instead of github, that should have the work done. 
https://github.com/bitfinexcom/bfx-api-node-util/pull/10

**Comment by chrisLeeTW** [comment]
@ezewer It will not be working if you use this command to install - `npm install --only=production`, which will not install dependencies from `devDependencies` sections. ):

**Comment by ezewer** [comment]
@chrisLeeTW ohh i see whats your issue, just sent a commit for this.

**Comment by chrisLeeTW** [comment]
@ezewer thanks for your quick response. 

By the way, this "returning to npm instead of github" problem is also seeing in your another repository - like bfx-api-node-models, bfx-api-node-rest and bfx-api-node-ws1.

**Comment by chrisLeeTW** [comment]
@ezewer And just for an reference. Maybe you can checkout this project - lernajs (https://github.com/lerna/lerna), which may solve this kind of dependencies problem.

lernajs is monorepo framework, we currently also use it for our one nodejs project, which also have multiple packages and some package is the core dependency of another.

**Comment by ezewer** [comment]
@chrisLeeTW thanks for marking this, would fix them! :+1:

**Comment by JacobPlaster** [comment]
@chrisLeeTW im not sure what you mean by "returning to npm instead of github problem is also seeing in your another repository". I understand the original devDeps issue but why is github SymVer causing problems?
